name: Check submodules
'on':
  pull_request: null
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true
permissions:
  contents: read
jobs:
  checks:
    timeout-minutes: 20
    environment:
      name: development
    env:
      DATABASE_URL: postgres://
      AUTH_SECRET: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha || github.sha }}
    - uses: ./.github/actions/submodules-checkout
      with:
        submodules-ssh-key: ${{ secrets.PRIVATE_GITHUB_DEPLOY_TOKEN }}
    - name: Check if any submodule branch matches github.ref_name
      run: "echo \"C ${{ github.workflow }}-${{ github.event.number || github.sha\
        \ }}\"\n# Get the current branch or tag name\nREF_NAME=\"${{ github.event.pull_request.head.ref\
        \ || github.ref_name }}\"\n\necho \"Branch is:\" $REF_NAME\n\n# List all submodule\
        \ paths\nSUBMODULES=$(git submodule status | awk '{print $2}')\n\n# Check\
        \ each submodule's branch\nfor SUBMODULE in $SUBMODULES; do\n  echo \"Checking\
        \ submodule: $SUBMODULE\"\n  (\n    cd \"$SUBMODULE\"\n    # Get the current\
        \ branch of the submodule\n    SUBMODULE_BRANCH=$(git rev-parse --abbrev-ref\
        \ HEAD)\n    echo \"Submodule branch: $SUBMODULE_BRANCH\"\n\n    # Compare\
        \ the submodule branch to the ref_name\n    if [ \"$SUBMODULE_BRANCH\" = \"\
        $REF_NAME\" ]; then\n      echo \"::error::Submodule '$SUBMODULE' is on branch\
        \ '$SUBMODULE_BRANCH', which matches the current ref '$REF_NAME'.\"\n    \
        \  exit 1\n    fi\n  )\n  if [ $? -ne 0 ]; then\n    exit 1 # Fail the workflow\
        \ if any submodule branch matches\n  fi\ndone\n\necho \"No submodule is on\
        \ the same branch as the current ref '$REF_NAME'.\"\n"
